BeeKeeper 0.2

Programm zum verwalten von Bienenvölkern:
Behalten sie alles im Blick!

Copyright (C) 2015 Daniel Knüttel

Lizenz: GNU AGPL v3 
(https://www.gnu.org/licenses/agpl-3.0.html)

Der Autor gibt keinerlei Garantie für das Programm, nicht einmal, das es einem 
bestimmten Zweck dient. Benutzung ist KOMPLETT auf EIGENE GEFAHR!

Installation:
./install.sh

Aufruf:
BeeKeeper

Nach dem ersten Aufruf kann man den Icon in den Starter ziehen.

Daniel Knüttel 2015

